[project]
name = "com-time-model"
version = "1.0.0"
description = "A clock widget for Class Widgets 2."
authors = [
    {name = "ClassWidgets User"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["class-widgets-sdk>=0.6.0"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
